### ISSUE TITLE
✨[feature] 메인페이지 내 노래방연결 컴포넌트 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#10]
In GitLab by @lilyjo128 on Sep 16, 2024, 15:35

### ✔️TODO
- [x] 노래방 연결모드 컴포넌트 디자인
- [ ] 노래방 모드 페이지 구현
- [ ] 큐알 코드 인식 페이지 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 16, 2024, 15:37

created branch [`feature/front/mainpageLinkmode-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FmainpageLinkmode-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 16, 2024, 23:59

marked the checklist item **노래방 연결모드 컴포넌트 디자인** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 17, 2024, 02:12

mentioned in commit 0fccded1604cb9b80f89d3fac55e74cb5b46be1a

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 19, 2024, 01:40

mentioned in commit 2640bb1b25bcf0ef01eb37cdc50407c6e7c7828f

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 19, 2024, 13:31

mentioned in commit dfb1833d995c907070339329f8dbe51eedb9f901

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 19, 2024, 13:46

mentioned in commit 4093ae0621ce7e1b3422f9831022005b87a76fbf

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 19, 2024, 13:46

mentioned in commit 26874f7a1725457dfec09a6e429e892f535b8a80
