### ISSUE TITLE
✨[feature] 그룹 상세페이지 API 연동

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#105]
In GitLab by @pjy7244 on Oct 1, 2024, 14:14

### ✔️TODO
- [x] 그룹초대 컴포넌트 구현
- [x] 곡 목록 컴포넌트 구현
- [x] 그룹초대 API 연동

### 📌ETC
- 그룹 나가기 수정

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 1, 2024, 14:14

created branch [`feature/front/groupDetail-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FgroupDetail-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 1, 2024, 21:05

marked the checklist item **그룹초대 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 1, 2024, 21:05

marked the checklist item **그룹초대 API 연동** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 2, 2024, 03:10

marked the checklist item **곡 목록 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 2, 2024, 03:12

mentioned in commit 3ce0cb6b7d13c62195e445e00da1ea5cda863393

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 03:52

mentioned in commit 1f2803471e68234c1d9888e489449ce9081cb9fd
