### ISSUE TITLE
✨[feature] 검색 페이지 컴포넌트 제작

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#106]
In GitLab by @lilyjo128 on Oct 1, 2024, 15:28

### ✔️TODO
- [x] 검색창 컴포넌트 제작
- [x] 최근 검색어 컴포넌트 제작
- [x] 최근 검색어 로컬스토리지 저장
- [x] 검색 시 검색분류별 탭 전환페이지 만들기

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 01:58

marked the checklist item **최근 검색어 컴포넌트 제작** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 01:58

marked the checklist item **검색 시 검색분류별 탭 전환페이지 만들기** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 01:58

marked the checklist item **최근 검색어 컴포넌트 제작** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 01:58

marked the checklist item **최근 검색어 컴포넌트 제작** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 01:58

marked the checklist item **검색창 컴포넌트 제작** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 2, 2024, 02:08

mentioned in commit 83d424892496b5ea15b406ed063ebeca95fefe4a
