### ISSUE TITLE
🐛[hotfix] 기록 조회 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#111]
In GitLab by @eunjee0404 on Oct 2, 2024, 09:29

### ✔️TODO
- [x] 최근 기록 조회 시 songId 반환 추가
- [x] 가장 많이 부른 기록 조회 시 memberId -> member 수정
- [x] Like 여부 확인 로직 수정

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 09:31

created branch [`hotfix/back/songHistory-eunji`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Fback%2FsongHistory-eunji) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 10:56

marked the checklist item **최근 기록 조회 시 songId 반환 추가** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 10:56

marked the checklist item **가장 많이 부른 기록 조회 시 memberId -> member 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 10:56

marked the checklist item **Like 여부 확인 로직 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 11:00

mentioned in commit 429d74633217611fc9cfe52f5b3defe36ce914d1

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 2, 2024, 11:05

mentioned in commit 804d880fe1fc9c1ed514f20421bd46f665062d6a
