### ISSUE TITLE
🐛[hotfix] 그룹 API 최적화

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#113]
In GitLab by @jerry5230 on Oct 2, 2024, 09:51

## 🐛[hotfix] 그룹 API 최적화
그룹 초대 로직 최적화

### ✔️TODO
- [ ] 그룹 초대 로직 필터링 제거
- [ ] 그룹 수정 이미지 처리 수정
- [ ] 그룹 생성 이미지 처리 수정

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 2, 2024, 09:51

created branch [`hotfix/back/teamRevision-suhwan`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Fback%2FteamRevision-suhwan) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 2, 2024, 17:41

mentioned in commit aeb2994816603eab97852a96711c2031927754a4

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 3, 2024, 06:22

mentioned in commit 3967fc186cd5b4455a39e1206891e477a8a500f5

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 3, 2024, 06:23

mentioned in commit 7ee70f1709dca7d348ddc8dece22e6ad4f366199
