### ISSUE TITLE
🐛[hotfix] Likes, History 엔티티 생성 방식 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#118]
In GitLab by @eunjee0404 on Oct 2, 2024, 12:54

### ✔️TODO
- [x] Likes, History 엔티티 생성 방식 수정
- [x] Java 컨벤션 맞추기
- [x] hashCode override 추가

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 12:55

created branch [`hotfix/back/entityCreate-eunji`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Fback%2FentityCreate-eunji) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 13:53

marked the checklist item **Likes, History 엔티티 생성 방식 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 13:53

marked the checklist item **Java 컨벤션 맞추기** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 13:54

marked the checklist item **hashCode override 추가** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 2, 2024, 13:57

mentioned in commit 2309f6a55ca10ebd809310f11b1a565816f78ce2
