### ISSUE TITLE
✨[feature] 알림 API 연동

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#130]
In GitLab by @pjy7244 on Oct 4, 2024, 22:39

### ✔️TODO
- [x] 읽지 않은 알림 여부 연결
- [x] 알림 목록 조회 연결
- [x] 알림 상세 조회 연결
- [x] 알림 읽음 연결
- [x] 알림 삭제 연결
- [x] 알림 초대 응답 연결

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 11:45

marked the checklist item **알림 목록 조회 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 11:51

marked the checklist item **알림 읽음 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 12:09

marked the checklist item **알림 삭제 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 12:52

marked the checklist item **읽지 않은 알림 여부 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 14:41

marked the checklist item **알림 상세 조회 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 15:02

marked the checklist item **알림 초대 응답 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 5, 2024, 17:51

mentioned in commit 0b3ef62455ab5bbc917573ae2aca0a9d0450fc33

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 5, 2024, 17:55

mentioned in commit a7efb32a2a62dbbe3998dc66c90a0c12ce418f1b
