### ISSUE TITLE
✨[feature] 연결상태 확인 API 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#138]
In GitLab by @lilyjo128 on Oct 6, 2024, 19:59

### ✔️TODO
- [x] checkConnectionStatus 응답 값 수정
- [x] 노래방 연결 시 모드 받아오기
- [x] 노래방 연결 시 그룹모드일 때, 팀 이름 받아오기
- [x] 그룹모드 api 연동하기

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 6, 2024, 19:59

created branch [`feature/front/connection-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Fconnection-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 6, 2024, 23:48

marked the checklist item **노래방 연결 시 그룹모드일 때, 팀 이름 받아오기** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 6, 2024, 23:48

marked the checklist item **그룹모드 api 연동하기** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 6, 2024, 23:48

marked the checklist item **노래방 연결 시 모드 받아오기** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 6, 2024, 23:48

marked the checklist item **checkConnectionStatus 응답 값 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 6, 2024, 23:49

mentioned in commit e984447b016cab883afdffe508b8cff49e7e07d3

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 6, 2024, 23:56

mentioned in commit c4e3cc9ca619f1e716256df5378eba9f439a167a
