### ISSUE TITLE
✨[feature] 테마별 추천 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#139]
In GitLab by @w01085914442 on Oct 6, 2024, 21:13

### ✔️TODO
- [x] 테마 목록 전체 조회 개발
- [x] 테마 목록 랜덤 조회 기능 개발
- [x] 테마별 노래 20곡 조회 기능 개발

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 6, 2024, 21:15

created branch [`feature/back/theme-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2Ftheme-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 7, 2024, 13:03

created branch [`feature/back/theme-eunji`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2Ftheme-eunji) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 7, 2024, 17:23

mentioned in commit 894419c68fea60c721795a0dec0844b9286648af

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 7, 2024, 17:26

marked the checklist item **전체 테마별 추천 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 8, 2024, 06:39

mentioned in commit 3ea91af3810d44ea67ca55009217f626dc0c4c34

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 8, 2024, 06:42

marked the checklist item **테마 목록 랜덤 조회 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Oct 8, 2024, 06:42

marked the checklist item **테마별 노래 20곡 조회 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 8, 2024, 06:56

mentioned in commit cbb999780acd6245afae776929f9e75ce4b8e89d
