### ISSUE TITLE
✨[feature] 로그인 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#14]
In GitLab by @w01085914442 on Sep 18, 2024, 20:14

### ✔️TODO
- [x] 인증/인가 필터 생성
- [x] JWT(Access, Refresh) 발급
- [x] Access Token 재발급
- [x] 로그인 기능 개발
- [x] 로그아웃 기능 개발
- [x] 회원가입 비밀번호 암호화 적용

### 📌ETC
- Spring Security 의존성 추가
- JWT 의존성 추가

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 20:15

created branch [`feature/back/login-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2Flogin-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 20:36

marked the checklist item **회원가입 비밀번호 암호화 적용** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:11

marked the checklist item **로그인 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:11

marked the checklist item **로그인 기능 개발** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:11

marked the checklist item **JWT(Access, Refresh) 발급** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:11

marked the checklist item **로그인 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:11

marked the checklist item **인증/인가 필터 생성** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:12

marked the checklist item **Access Token 재발급** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:33

marked the checklist item **로그아웃 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:42

mentioned in commit 3202d359a8c23221539d36d9df474f74430c9139

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:42

mentioned in commit 7c2b599c4cfe760440c334aaa5a4efbce98b691f

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:42

mentioned in commit f027104a7a8e8860e85bb8b88362833f80fd8630

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:42

mentioned in commit 143fbb941f78590da1237e974a1ed079e31fd692

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:42

mentioned in commit edbbf40965b2cdfe972cf053d49ee9794000a4a0

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 03:46

mentioned in commit a125ddf554c933fb0d886544cfbdea54c7375d2f
