### ISSUE TITLE
✨[feature] 아이디 비밀번호 찾기 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#147]
In GitLab by @pjy7244 on Oct 7, 2024, 13:44

### ✔️TODO
- [x] 아이디 찾기 컴포넌트 구현
- [x] 비밀번호 찾기 컴포넌트 구현
- [x] 아이디 찾기 api 연동
- [x] 비밀번호 찾기 api 연동

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 7, 2024, 14:40

created branch [`feat`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feat) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 7, 2024, 14:41

created branch [`feature/front/findAccount-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FfindAccount-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 01:22

marked the checklist item **아이디 찾기 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 01:22

marked the checklist item **비밀번호 찾기 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 01:22

marked the checklist item **아이디 찾기 api 연동** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 01:22

marked the checklist item **비밀번호 찾기 api 연동** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 01:23

mentioned in commit 831b2a98ad2b2a48629fd80fe1f1f65a2dc0e6e2

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 01:27

mentioned in commit 103b951f1772d537d11c26f35d45f78425c63c31
