### ISSUE TITLE
✨[feature] 마이페이지 프로필 수정 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#149]
In GitLab by @kminjin99 on Oct 7, 2024, 14:45

### ✔️TODO
- [ ] 프로필 사진 수정 구현
- [x] 닉네임 수정 구현
- [x] 전화번호 수정 구현
- [ ] 비밀번호 재설정 구현
- [ ] 프로필 수정 api 연결

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 7, 2024, 14:46

created branch [`feature/front/changeProfile-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FchangeProfile-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 7, 2024, 17:53

mentioned in commit bb54aa32a9713c4da09d26f96528da6c9eacaf15

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 7, 2024, 17:55

marked the checklist item **프로필 수정 페이지 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 7, 2024, 17:55

marked the checklist item **프로필 수정 페이지 구현** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 7, 2024, 17:55

mentioned in commit f21b852c608aa5f5536ff43c917309ecf181d4a0

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 8, 2024, 18:00

mentioned in commit 663538ce1082575ebd7c3602a6352f686829da2d

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 8, 2024, 18:00

mentioned in commit 5cf00ef947c66e83537b9512a6fe31d6d21602ad

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 8, 2024, 18:00

mentioned in commit 107451ddaa96e727f0119ceaa6216aa4f7d6bc30

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 8, 2024, 18:01

mentioned in commit 39d54a35b536d65f3fbbc09e4ea34fd34036b380

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 9, 2024, 24:02

marked the checklist item **닉네임 수정 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 9, 2024, 24:02

marked the checklist item **전화번호 수정 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 9, 2024, 24:03

mentioned in commit e57d5cd898d3a61c6c5a0e8ce84b82e6fb700a26

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 9, 2024, 17:45

mentioned in commit 57bf5f6d08d134e6a9f44df1ae2a1e1703c19c4f

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 9, 2024, 17:45

mentioned in commit 746b4b2947054f34686639d587c1a79889bd9037

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 17:51

mentioned in commit efd481067b1dbe7d9deb6a1f079960e06a4c62ce

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit e814eefe4a61a370f02b947032a54fcc255f3965

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit cddcef77f4845db9741d4e0cb16f2a2174658648

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit a32f925227f3f24f94e7127c378bdc1e92821ef0

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit 4e44220807ba0d91aef8c88e3e35557a4622d24d

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit 9fd277bea9f30db9671a0aeef289b8d4591973f0

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit d7e11404944127e341be873cb1c524ee367fed38

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 14, 2024, 13:35

mentioned in commit b13230b5126b677491d4813905acf4b893dd52bb
