### ISSUE TITLE
✨[feature] 회원 초기 곡선택 페이지 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#15]
In GitLab by @pjy7244 on Sep 18, 2024, 23:09

### ✔️TODO
- [x] 곡선택 페이지 구현
- [x] 선택 데이터 항목 api 연동
- [x] 초기 데이터 선택 api 연동
- [x] store에 곡선택 여부 저장

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 18, 2024, 23:18

created branch [`feature/front/signupSong-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FsignupSong-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 19, 2024, 17:00

created branch [`feature/front/userSongPick-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FuserSongPick-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 23, 2024, 09:28

mentioned in commit d658736c410cf9fa80334795540b951ff75d5913

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 23, 2024, 12:55

mentioned in commit 726251060e4684b8cfd9c1f1b05c06d71a917ef3

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 25, 2024, 15:29

mentioned in commit f5a84ddcbdfed44e5731cb05d612177ae98e9859

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 26, 2024, 09:44

created branch [`feature/front/userSongPick-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FuserSongPick-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 26, 2024, 18:01

mentioned in commit f4b2ddaf52492a40c32e6e95844f31585be529a4

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 02:06

marked the checklist item **곡선택 페이지 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 02:06

marked the checklist item **선택 데이터 항목 api 연동** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 02:06

marked the checklist item **초기 데이터 선택 api 연동** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 02:06

mentioned in commit e2f77a66c2eac568abd76da91d4f1dbffe71ca05

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 09:51

mentioned in commit c778a8e568a4a1ca18480f4b665b99e112447156

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 27, 2024, 09:56

mentioned in commit 6755c8a8d6f7bc3a18c31e8f2a32c3d46dd9589e
