### ISSUE TITLE
✨[feature] 테마페이지 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#151]
In GitLab by @lilyjo128 on Oct 7, 2024, 20:34

### ✔️TODO
- [x] 테마 페이지 탭 전환 구현
- [x] 추천테마 api 연동
- [x] 테마페이지 찜하기 구현
- [x] 테마페이지 예약하기 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 7, 2024, 20:35

created branch [`feature/front/themepage-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Fthemepage-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 01:12

mentioned in commit 7180ba67064d550f3a2fd6b99b8aa4ede45ce2ca

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 01:20

mentioned in commit 4d98c334865f2768055dea835fc5e531a15b46aa

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 11:59

mentioned in commit 18610b776d55aab168b7f0fe710007790277d028

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 12:03

mentioned in commit 43dc945af87cea20228aa37ccd736d3b0d04e6a0

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 8, 2024, 12:05

mentioned in commit 432a42a1db24ef47839895702f60a1c5d4ba4b09

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 14:54

mentioned in commit 06fef64849e3ebc5eb2e815bea3a0540fa68430a

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 14:56

marked the checklist item **테마 페이지 탭 전환 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 14:56

marked the checklist item **추천테마 api 연동** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 14:56

marked the checklist item **테마페이지 찜하기 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 8, 2024, 14:56

marked the checklist item **테마페이지 예약하기 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 8, 2024, 14:57

mentioned in commit 446eceeed6321b27b44d25b5c10b013a3e2bb3cc

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 14, 2024, 13:35

mentioned in commit 457549388b8f3e8bcddb6d9ad57f6adf62e5d8ae

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit d4a1f3f00980a48d1972ec89d3ab2385f69c1ac2
