### ISSUE TITLE
🐛[hotfix] Song 관련 서비스 리팩토링

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#155]
In GitLab by @jerry5230 on Oct 8, 2024, 10:20

## 🐛[hotfix] Song 관련 서비스 리팩토링
성능 개선

### ✔️TODO
- [ ] django 통신 예외처리
- [ ] findSongWithLikeStatus fetch join 적용
- [ ] @Transactional(readOnly = true) 추가
- [ ] django 통신 비동기로 변환

### 📌ETC
개선할지 고민중인 사항
- 검색엔진 Full-text search, Elasticsearch

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 8, 2024, 10:21

created branch [`hotfix/back/songRefactoring-suhwan`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Fback%2FsongRefactoring-suhwan) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Oct 14, 2024, 11:09

mentioned in commit 6e81beb0f8f2751d72c2b47f163b73228ada339f
