### ISSUE TITLE
🐛[hotfix] css 디자인 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#160]
In GitLab by @lilyjo128 on Oct 9, 2024, 15:40

### ✔️TODO
- [x] 마이리스트 모달 내 빈화면일때 글자조정
- [x] 폰트 CDN 변경
- [x] 마이페이지 빈화면일 때, 대체 텍스트설정

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 15:50

created branch [`160-hotfix-css`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...160-hotfix-css) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 15:51

created branch [`hotfix/front/fixcss-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2Ffixcss-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 17:02

mentioned in commit 0276b782569891edb4b941f29289030b332a3dce

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 9, 2024, 17:17

mentioned in commit e7788d36843e35d1c130103aff8e2b29b650fbc2

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 17:38

mentioned in commit 1662bfc76fd0435b1b448bb0af1f4a46063ee2ad

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 9, 2024, 17:40

mentioned in commit 518f3935ac3ebfe286f8c709b2f5283944d7f63b

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 18:33

mentioned in commit eb27bce0bab358de0e44664051151fdf9582c8f8

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 9, 2024, 18:35

mentioned in commit a37e14a53df986cca8b8efcc104901166fe85ff0

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 19:03

mentioned in commit 09e66c87001cc3f86dc33c6b8e44c43fa9bc09d4

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 9, 2024, 19:05

mentioned in commit 09714a1cb0623025847bae86a53057430eebef63

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 19:35

mentioned in commit 55a653ac4c6a5ffb3807bab0d5378ef0409205e8

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 9, 2024, 19:37

mentioned in commit f32e83e7ee207c2ef73a69c6e6c4f5ccfb36c5d6

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 20:21

mentioned in commit c3d613f1f46d6ebeb64de87964248105a612de5c

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 20:23

marked the checklist item **마이리스트 모달 내 빈화면일때 글자조정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 20:24

marked the checklist item **폰트 CDN 변경** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 9, 2024, 20:24

marked the checklist item **마이페이지 빈화면일 때, 대체 텍스트설정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 10, 2024, 09:15

mentioned in commit 79036b2d28bfada38210825f41e2a111f33b605d

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 11, 2024, 03:54

mentioned in commit f99021a7b8d27ce22dbec6de11a0de4710d0af01

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 11, 2024, 03:57

mentioned in commit 2ae34050ad4b884f054b7fb47ecc8bc8d73261ac

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit da3e33a9553c09ac3f21f834655270ade0e41cc1

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit 3c5132480d9257375cc47cf95b9665bc01014684

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 14, 2024, 13:35

mentioned in commit 400bca530ae7f5646f93a0c32af67ee2be42d200

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit 048a042bde784b3c38fd655eca339c4d79b21745

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit 77d1ed5376a46e502314fe20d733ded82e84e368

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit 1304428193df4cc28ba694674437830774a043df

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit 060a55160bdad2ab69daf8598c04fa9f3d545c4e

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 14, 2024, 13:35

mentioned in commit b4a28b89f52bcf5cd737f91af55418600ff4f021

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 14, 2024, 13:35

mentioned in commit 8bfac9110360187dc708fdcc6ec2d258620869bf

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit 625092edc11690c0cb2b06b366148fced05e2836

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 14, 2024, 13:35

mentioned in commit 78b634281c97554c966828183e0d976d9d15eabc

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 14, 2024, 13:35

mentioned in commit 64ec13518434d3d3fcce990c02fb24f4c5b18ed1

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 14, 2024, 13:35

mentioned in commit 13c082cb105e8ae2dc701f4f08a0300e3ed54f6d

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 14, 2024, 13:35

mentioned in commit 4f0920ea4367cd8fe6dc1aa81955969c047be618
