### ISSUE TITLE
✨[feature] 노래방 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#18]
In GitLab by @w01085914442 on Sep 19, 2024, 10:30

### ✔️TODO
- [x] 노래방 충전 기능 개발
- [x] 노래 시작 기능 개발
- [x] 예약 목록 확인 기능

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 19, 2024, 10:30

created branch [`feature/back/karaoke-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2Fkaraoke-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 20:21

marked the checklist item **노래 충전 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 23, 2024, 24:34

mentioned in commit a6135315920119cf2ff5035ef977db850d8be7e8

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 23, 2024, 02:10

mentioned in commit 03f28f42cd996183719bf8948e1b2723d9388389

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 23, 2024, 18:00

marked the checklist item **예약 목록 확인 기능** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 24, 2024, 11:16

mentioned in commit 7a17fc65978e7b702b42fb128bcad23ad2c210bf

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 24, 2024, 11:16

mentioned in commit fa17dd5361038504e0de1335295af092904b235a

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 24, 2024, 11:20

mentioned in commit 58babe51a5b2aa23a7a1fe89ba33de90d5bac6ec

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 24, 2024, 13:55

mentioned in commit 79b5505636b9c203e0db9452b95272112aba6eb7

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 03:23

marked the checklist item **노래 시작 기능 개발** as completed
