### ISSUE TITLE
✨[feature] 아이디찾기 컴포넌트 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#21]
In GitLab by @lilyjo128 on Sep 19, 2024, 13:57

### ✔️TODO
- [x] 아이디 찾기 라우터 연결
- [x] 비밀번호 찾기 라우터 연결
- [x] 아이디찾기 /비밀번호 찾기 탭 전환 컴포넌트 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 19, 2024, 13:59

created branch [`feature/front/FindId-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FFindId-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 19, 2024, 17:43

mentioned in commit bb0778aaa9ed69dec909cafbe8e18b0c5560f17d

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 11:05

marked the checklist item **아이디 찾기 라우터 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 11:05

marked the checklist item **비밀번호 찾기 라우터 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 11:05

marked the checklist item **아이디찾기 /비밀번호 찾기 탭 전환 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 11:10

mentioned in commit 138b04cc25c3c05da187160731a519b182815e1a

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 11:22

mentioned in commit 9f92a5fb86e9c880ca6640dd2aefa8d6d91b6dea

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 20, 2024, 13:24

mentioned in commit 1fc583309180f7ab70451f3100d3b94a4276d32b
