### ISSUE TITLE
✨[feature] 노래리스트 컴포넌트 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#28]
In GitLab by @lilyjo128 on Sep 20, 2024, 09:41

### ✔️TODO
- [x] 찜버튼 구현
- [x] 예약버튼 구현
- [x] 곡 번호 겹치는 앨범표지 컴포넌트구현
- [x] 가로형 노래리스트 컴포넌트 구현
- [x] 세로형 노래리스트 컴포넌트 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 09:42

created branch [`feature/front/musuclist-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Fmusuclist-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 14:44

created branch [`feature/front/Musiclist-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FMusiclist-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 18:04

mentioned in commit e5d049d9edac00cbac1c182b7ad997b989f0586e

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 09:45

marked the checklist item **찜버튼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 09:45

marked the checklist item **예약버튼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 09:45

marked the checklist item **곡 번호 겹치는 앨범표지 컴포넌트구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 09:45

marked the checklist item **곡 번호 겹치는 앨범표지 컴포넌트구현** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 09:45

marked the checklist item **예약버튼 구현** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 09:45

marked the checklist item **찜버튼 구현** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 16:34

mentioned in commit 86a4fb5658a51ffbb002064e244210624f874e66

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 23, 2024, 16:38

marked the checklist item **찜버튼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 23, 2024, 16:38

marked the checklist item **예약버튼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 23, 2024, 16:38

marked the checklist item **곡 번호 겹치는 앨범표지 컴포넌트구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 23, 2024, 16:38

marked the checklist item **가로형 노래리스트 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 23, 2024, 16:38

marked the checklist item **세로형 노래리스트 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 16:41

mentioned in commit 65eeb9af5c2d1b25fbff442127aa9b1e16101199
