### ISSUE TITLE
✨[feature] layout폴더 및 컴포넌트 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#29]
In GitLab by @pjy7244 on Sep 20, 2024, 10:48

### ✔️TODO
- [x] 상단 네브바 title props 추가
- [x] layout 폴더 생성
- [x] layout 컴포넌트 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 10:48

created branch [`feature/front/layout-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Flayout-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 10:49

marked the checklist item **상단 네브바 title props 추가** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 13:23

marked the checklist item **layout 폴더 생성** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 13:23

marked the checklist item **layout 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 13:24

mentioned in commit c68ed81feaccb11d4eb49278fe9b8eb104c7ddc6

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 20, 2024, 16:35

mentioned in commit a7df15d026712eb31fd401b58407b6969b8cd9ff
