### ISSUE TITLE
🐛[hotfix] 노래방 랜딩페이지 요소 크기 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#32]
In GitLab by @kminjin99 on Sep 20, 2024, 16:44

## 🐛[hotfix] 노래방 랜딩페이지 요소 크기 수정

랜딩페이지 안에 컴포넌트 및 요소들의 크기가 작아서 수정해야함
### ✔️TODO
- [x] 로고 크기 수정
- [x] 타이틀 크기 수정
- [x] 버튼 크기 수정

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 20, 2024, 16:46

created branch [`hotfix/front/karaokeLandingScale-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FkaraokeLandingScale-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 20, 2024, 17:00

mentioned in commit f16018821ed06d0873d7e787516e1f36f5e0a592

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 17:05

marked the checklist item **타이틀 크기 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 17:05

marked the checklist item **로고 크기 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 17:05

marked the checklist item **버튼 크기 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 17:05

mentioned in commit ff6b999ae61641f8b25b2a2bac8cb1933ddad8e3
