### ISSUE TITLE
✨[feature] 회원가입 중복 검사 API 연결

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#33]
In GitLab by @pjy7244 on Sep 20, 2024, 16:45

### ✔️TODO
- [x] 아이디 중복 검사 API 연결
- [x] 닉네임 중복 검사 API 연결
- [x] 전화번호 중복 검사 API 연결
- [x] 전화번호 인증코드 API 연결

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 16:50

created branch [`feature/front/idCheckAPI-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FidCheckAPI-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 20, 2024, 16:53

created branch [`feature/front/signupCheckAPI-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FsignupCheckAPI-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 15:21

mentioned in commit 29e1e072091ac7c21ca2f40eb0fb6dbeb4128d7e

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 18:58

mentioned in commit 0603776dcf3c939d44f1198447c84593171341a6

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 18:59

marked the checklist item **아이디 중복 검사 API 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 18:59

marked the checklist item **닉네임 중복 검사 API 연결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 18:59

marked the checklist item **전화번호 인증코드 API 연결** as completed
