### ISSUE TITLE
🐛[hotfix] react build 오류 수정 및 Health Check 삭제

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#34]
In GitLab by @w01085914442 on Sep 22, 2024, 24:22

### ✔️TODO
- [x] QR 인식 코드 수정
- [x] 안쓰는 import문 삭제
- [x] 백엔드 Health Check 코드 삭제

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:23

created branch [`hotfix/front/reactBuild-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FreactBuild-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:25

marked the checklist item **QR 인식 코드 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:25

marked the checklist item **안쓰는 import문 삭제** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:28

mentioned in commit 9d09467d2906de5577ac20561ebf996127ad1ddb

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:28

mentioned in commit c79403e287ff4c32d24fd764f967baa8e03406dc

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:29

marked the checklist item **백엔드 Health Check 코드 삭제** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 22, 2024, 24:31

mentioned in commit 6844f7968c3efb01039cfeb0e99206bf062c593e
