### ISSUE TITLE
✨[feature]  회원가입 기본정보 및 회원정보 페이지 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#4]
In GitLab by @pjy7244 on Sep 13, 2024, 15:47

### ✔️TODO
- [x] 회원가입 진행바 구현
- [x] 회원가입 진행 설명칸 구현
- [x] 회원가입 하단 버튼 구현
- [x] 회원가입 기본정보 폼 구현
- [x] 회원가입 회원정보 폼 구현

### 📌ETC
- 로그인 화면에서 form제출로 인한 새로고침 수정
- 스크롤바 숨기기를 위한 index.css 수정

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 13, 2024, 15:49

created branch [`feature/front/signup-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Fsignup-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 16, 2024, 11:41

created branch [`feature/front/login-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Flogin-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 17, 2024, 18:27

marked the checklist item **회원가입 진행바 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 17, 2024, 18:27

marked the checklist item **회원가입 진행 설명칸 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 17, 2024, 18:27

marked the checklist item **회원가입 하단 버튼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 17, 2024, 18:27

marked the checklist item **회원가입 기본정보 폼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 17, 2024, 23:43

marked the checklist item **회원가입 회원정보 폼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 17, 2024, 23:50

mentioned in commit ca90ff97caebbe43b2a5c875dc917d20eaf35cd3

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 18, 2024, 24:02

mentioned in commit c9cad809f8bab27648362fd73ce52e134baa57b6
