### ISSUE TITLE
🐛[hotfix] 회원가입 전화 번호 인증 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#41]
In GitLab by @pjy7244 on Sep 22, 2024, 20:40

### ✔️TODO
- [x] 회원가입 회원정보 인증 수정
- [x] 회원가입 회원정보 중복 수정
- [x] 회원가입쪽 eslint 적용

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 20:41

created branch [`hotfix/front/phoneAuth-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FphoneAuth-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 22:35

marked the checklist item **회원가입 회원정보 중복 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 22:35

marked the checklist item **회원가입 회원정보 인증 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 22, 2024, 22:38

mentioned in commit 327176107eca0ed51d0eced0d7e16519aa7393d4

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 22, 2024, 23:12

mentioned in commit b6bcdff9621298f7aa822d24bd9c43f587b233a9
