### ISSUE TITLE
🐛[hotfix] QR 코드 연결정보 저장소 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#47]
In GitLab by @lilyjo128 on Sep 23, 2024, 16:50

### ✔️TODO
- [x] 기존 주스탠드로 store 관리한 파일삭제
- [x] 서버통신으로 단기저장하도록 변경
- [x] 연결되어있지 않았을 때는 예약버튼 비활성화하기

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 23, 2024, 16:51

created branch [`hotfix/front/qrscan-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2Fqrscan-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 02:50

mentioned in commit db7aedcae613d820222efc9e4a6fd86f26ed6378

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 14:10

mentioned in commit 4735179f865e50f33a841de28202c6a3875219ce

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 14:21

marked the checklist item **기존 주스탠드로 store 관리한 파일삭제** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 14:22

marked the checklist item **서버통신으로 단기저장하도록 변경** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 14:22

marked the checklist item **연결되어있지 않았을 때는 예약버튼 비활성화하기** as completed

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 16:54

mentioned in commit 646d763efb7fe231c160192ee7d9bdf37cfd168e

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 17:00

mentioned in commit bd49f227bcfa9b83b75d48750cc76f9065bd0d8e

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 24, 2024, 17:00

mentioned in commit 23cb94fd13a7daccbf1b9674dd112e58ebe713f7
