### ISSUE TITLE
✨[feature] 마이리스트 모달창 디자인

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#55]
In GitLab by @lilyjo128 on Sep 24, 2024, 17:52

### ✔️TODO
- [x] 상단navbar의 나의 재생목록 모달 구현
- [x] 찜한곡 및 최근 부른곡 탭 전환버튼 구현
- [x] 휴대폰 뒤로가기 버튼으로 모달창 닫히도록 만들기

### 📌ETC
- 사용자 로그인 및 리스트 받아오면 그때 api 연동 예정

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 24, 2024, 17:52

created branch [`feature/front/musicModal-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FmusicModal-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 14:34

mentioned in commit 76f1fe12cec6e7d84e9c0881949b26d6498bc1ec

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 14:34

mentioned in commit 95f6ce915a17044118593e9f2dbd59b60862b429

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Oct 2, 2024, 14:37

mentioned in commit f4292cba19a75bdc2b62aa0f0b45248172ab14ee

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 2, 2024, 17:15

mentioned in commit 8294b977e62892d0cc059943ce055d33b28f220b

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 3, 2024, 18:49

mentioned in commit fc1167cb2d7a29b1560d8c04b38d6ad1cbd27fa3

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Oct 4, 2024, 17:53

mentioned in commit 46013173e34f0d1aef8e24480b911d04bd5713ec

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Oct 4, 2024, 17:55

mentioned in commit c02abe3b5b550656e0008b7c852d925ce48657de
