### ISSUE TITLE
✨[feature] 노래방 예약 목록 & 미니 추천 차트 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#57]
In GitLab by @kminjin99 on Sep 25, 2024, 24:31

## ✨[feature] 노래방 예약 목록 & 미니 추천 차트 구현

유튜브 연결 화면에서 예약 목록과 미니 추천 차트를 확인할 수 있게 함
### ✔️TODO
- [x] 예약 목록 & 추천 차트 확인 버튼 구현
- [x] 예약 목록 구현
- [x] 추천 차트 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 25, 2024, 24:32

created branch [`feature/front/karaokeMiniChart-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FkaraokeMiniChart-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 25, 2024, 17:42

mentioned in commit 2ffd04032fa141723c968fc95cf50d806e579de3

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 26, 2024, 10:40

mentioned in commit f14be531acd8464815fc2b658b77b586714cf400

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 17:01

mentioned in commit 98910a0a82bdfa5b1daf1d7b8e884c6b08767009

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 17:01

mentioned in commit ed214cc4d87b702b1f41864d1b296eafb0ebe6e8

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 09:45

mentioned in commit be4ce37080a0db182f43d5c8e41fbae8f04d2e43

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 29, 2024, 18:37

mentioned in commit ebae49b4ae05fbe27709993b67347ed5463803d9

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 29, 2024, 18:37

marked the checklist item **예약 목록 & 추천 차트 확인 버튼 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 29, 2024, 18:37

marked the checklist item **예약 목록 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 29, 2024, 18:37

marked the checklist item **추천 차트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 29, 2024, 19:23

mentioned in commit f6c9b63e306b909478a853b7290054805493e272
