### ISSUE TITLE
✨[feature] 회원가입 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#6]
In GitLab by @w01085914442 on Sep 15, 2024, 14:38

### ✔️TODO
- [x] 아이디 중복 검사 기능 개발
- [x] 닉네임 중복 검사 기능 개발
- [x] 전화번호 중복 검사 기능 개발
- [x] 전화번호 인증 코드 전송
- [x] 전화번호 인증 코드 확인
- [x] 회원가입 기능 개발

### 📌ETC
- 인증 관리를 위한 RedisConfig 파일 작성
- sms 서비스 사용을 위한 의존성 추가
- s3 파일 업로드 기능 개발

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 15, 2024, 14:39

created branch [`feature/back/signup-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2Fsignup-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 16, 2024, 10:59

marked the checklist item **아이디 중복 검사 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 16, 2024, 11:09

marked the checklist item **닉네임 중복 검사 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 16, 2024, 14:35

marked the checklist item **전화번호 중복 검사 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 17, 2024, 19:55

mentioned in commit 61bb992aa1fe8c5e22b4e682c544638a08766d9c

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 17, 2024, 19:55

mentioned in commit 6e0c168edf9163a0868522da7743fc3d5b454261

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 17, 2024, 19:55

mentioned in commit 48c3807c4bb10608eab3c713f5f420f8e2198f32

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 24:07

marked the checklist item **전화번호 인증 코드 전송** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 24:07

marked the checklist item **전화번호 인증 코드 확인** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 14:07

marked the checklist item **회원가입 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:43

mentioned in commit d953d00766303a94220e48b7ae7cf81319da1bc1

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:43

mentioned in commit 506cfdaf65cdfcb1ab6549432b9f1f5fe6af6b79

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:43

mentioned in commit fae7a31795c3ac1e61ef829b86b67c682e3fc8da

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:43

mentioned in commit 787af071fd1c52a34ec13dffcf12c8a537a3ae99

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:46

mentioned in commit f5aa850b903fe7edf852072ce1306c281b2df86c

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:46

marked the checklist item **회원가입 기능 개발** as incomplete

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:46

marked the checklist item **회원가입 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:48

mentioned in commit e2fadfc7397a810541257ab0f6f184a17d52f2b8

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:50

mentioned in commit cc080489bb51d0c69beabf5bda9ef2a01fae795f

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 19:53

mentioned in commit 1a622a3c8c5c12370fe8e9d1b1705f511f28cc7f

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 18, 2024, 20:05

mentioned in commit 48e057d290332c7fbdb44538e83e2da214b4da32
