### ISSUE TITLE
🐛[hotfix] 서비스 연동 api 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#61]
In GitLab by @w01085914442 on Sep 25, 2024, 04:58

### ✔️TODO
- [x] 노래방 충전 여부 검사 로직 수정
- [x] 여러 기기 연결 문제 해결 
- [x] 연동 api 반환값 추가
- [x] 예약 api 수정

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 04:58

created branch [`hotfix/back/connection-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Fback%2Fconnection-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 06:45

marked the checklist item **노래방 충전 여부 검사 로직 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 06:45

marked the checklist item **여러 기기 연결 문제 해결** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 06:46

marked the checklist item **연동 api 반환값 추가** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 07:13

marked the checklist item **예약 api 수정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 07:13

mentioned in commit 177f757f0a2f4b1051d4c7bf1e5d12d9b8b56085

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 07:16

mentioned in commit 3795c8eb56afdb79bbc74af119a36d4bbf4924c1

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 25, 2024, 17:46

mentioned in commit c8b5fa9896d3ed9966aec411302fdde3d163f9bf
