### ISSUE TITLE
✨[feature] 찜 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#62]
In GitLab by @eunjee0404 on Sep 25, 2024, 09:47

### ✔️TODO
- [x] 찜 등록 기능 개발
- [x] 찜 삭제 기능 개발
- [x] 찜 목록 조회 기능 개발

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 25, 2024, 09:49

created branch [`feature/back/likes-eunji`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2Flikes-eunji) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 25, 2024, 17:46

mentioned in commit b71996103141f44875029100727902b655a04d30

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 25, 2024, 17:53

marked the checklist item **찜 등록 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 25, 2024, 17:53

marked the checklist item **찜 삭제 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 25, 2024, 17:53

marked the checklist item **찜 목록 조회 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 26, 2024, 03:50

mentioned in commit ca0a3bec99fc805d03c4465981620e4ef3de9af0

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 26, 2024, 03:50

mentioned in commit af5ba82fd40fe21311ed80f8a7d6c92198512987
