### ISSUE TITLE
✨[feature] 알림창 모달 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#69]
In GitLab by @lilyjo128 on Sep 25, 2024, 17:28

### ✔️TODO
- [ ] 상단 네브바 내 알림아이콘 클릭 시 모달 뜨도록 구현
- [ ] 알림 컴포넌트 제작 : 사용자 초대 알림
- [ ] 초대 알림 클릭 시, 그룹세부사항 모달 컴포넌트 제작

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 25, 2024, 17:31

created branch [`feature/front/alertmodal-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Falertmodal-soyeon) to address this issue
