### ISSUE TITLE
✨[feature]  로그인 페이지 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#7]
In GitLab by @pjy7244 on Sep 16, 2024, 11:40

### ✔️TODO
- [x] 아이디 인풋 컴포넌트 구현
- [x] 비밀번호 인풋 컴포넌트 구현
- [x] 로그인 버튼 컴포넌트 구현
- [x] 아이디, 비밀번호 찾기 버튼 컴포넌트 구현
- [x] 회원가입 버튼 컴포넌트 구현

### 📌ETC
- atoms/commos/PasswordVisibilityToggle 추가: 비밀번호 보기/ 숨기기 토글
- molecules/commons/SubTopNavbar 추가: 하단 내브바에 포함된 페이지들 외의 다른 페이지들에 사용되는 상단 내브바 추가
(props로 title넘겨서 위에 이름 변경하면됨 ex)회원가입, 로그인 등)
- daisyUI 컬러 변경: tailwind.config.js 수정
- App.tsx 라우터 수정: 하단 내브바에 포함된 페이지들 외의 다른 페이지들에는 TopNavbar 적용안되게 변경

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 16, 2024, 15:09

marked the checklist item **아이디, 비밀번호 찾기 버튼 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 16, 2024, 15:50

created branch [`feature/front/login-juyeong`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Flogin-juyeong) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 16, 2024, 16:04

mentioned in commit 90d6401b6643e9d524cfaa1a929386169f22674c

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 16, 2024, 16:32

mentioned in commit 71d6b8a1fd5f55639ebe0300834e27a012cc9f11
