### ISSUE TITLE
✨[feature] 메인페이지 버튼 및 노래상세페이지 모달 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#75]
In GitLab by @lilyjo128 on Sep 26, 2024, 09:41

### ✔️TODO
- [ ] 연결해제 버튼 컴포넌트 제작
- [ ] 새로고침 버튼 컴포넌트 제작
- [ ] 노래상세페이지 모달 컴포넌트 제작

### 📌ETC
- 휴대폰 뒤로가기버튼으로 모달 닫기도록 하기
- 모달 이외의 부분 터치 및 슬라이드 시 닫기도록 하기

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 26, 2024, 09:41

created branch [`feature/front/musicdetail-soyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2Fmusicdetail-soyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 26, 2024, 17:59

mentioned in commit 03377263bcbe77de051fb3357ea8e92bbed50c96

**Comment by hyeon8571** [comment]
In GitLab by @lilyjo128 on Sep 27, 2024, 09:18

mentioned in commit 6ca9b6338782e559c91bfc484a8879ee56b659d7

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 27, 2024, 09:18

mentioned in commit fac55b14fdcb9a63b4f3305419c16d5e05bb5e92
