### ISSUE TITLE
🐛[hotfix] 노래방 라우터 경로 수정

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#77]
In GitLab by @kminjin99 on Sep 26, 2024, 13:51

### ✔️TODO
- [x] 경로에서 karaoke 제거
- [x] base 경로에 karaoke 설정
- [x] 전체 경로 점검

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 13:52

created branch [`hotfix/front/karaokeRemove-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FkaraokeRemove-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 13:55

mentioned in commit a82db5f2a26870df95e0b4c2a2748f5c7f895347

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 26, 2024, 13:58

mentioned in commit 072017ada3e836981df92a1cba771ad01e2031a7

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 16:01

marked the checklist item **경로에서 karaoke 제거** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 16:02

created branch [`hotfix/front/karaokeBase-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FkaraokeBase-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 16:06

mentioned in commit db3f2fb84fe27280afaf1650c9934e6797ef5757

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 16:08

marked the checklist item **base 경로에 karaoke 설정** as completed

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 26, 2024, 16:09

mentioned in commit 591fbf2cc0a5ca3df280a9388b076aaddb7c82e6

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 16:58

created branch [`hotfix/front/karaokeTs-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FkaraokeTs-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 17:03

mentioned in commit f2b77225484d0c58347b44fd999a27919c33cace

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 26, 2024, 17:05

mentioned in commit 05aff4d57554d9c554ee71f3f22d54ba059f63ab

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 26, 2024, 17:15

created branch [`hotfix/front/karaokeRoutesAll-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...hotfix%2Ffront%2FkaraokeRoutesAll-minjin) to address this issue
