### ISSUE TITLE
✨[feature] 노래방 결제 페이지 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#8]
In GitLab by @kminjin99 on Sep 16, 2024, 14:49

### ✔️TODO
- [x] 결제 단위 컴포넌트 구현
- [x] 노래방 결제 페이지 구현
- [x] 결제 관련 모달창 구현

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 16, 2024, 14:54

created branch [`feature/front/karaokePaying-minjin`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Ffront%2FkaraokePaying-minjin) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 17, 2024, 01:34

mentioned in commit 5ba74027a5b265681c1bf1afecdf33c433ded25e

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 17, 2024, 01:34

mentioned in commit 219cdc18f8ce2d6fa0b37521deda075446dec9f8

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 17, 2024, 01:34

mentioned in commit c5ab28289b77444fd9fc72a0f279b5f5a2cea08b

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 17, 2024, 01:34

mentioned in commit b00b3b7071dc92e0a073f15cb73c27337828701b

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 17, 2024, 01:34

mentioned in commit 82848971259dff9269ad1f4c52bfbfc7a990766a

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 17, 2024, 01:34

mentioned in commit a0e8a870ba6d009bc2d8124b5c773d0d75d43529

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 18, 2024, 18:26

mentioned in commit 7f484ce9cb082e688322189e2b1b9b67f254fabc

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 18, 2024, 18:27

marked the checklist item **결제 단위 컴포넌트 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 18, 2024, 18:27

marked the checklist item **노래방 결제 페이지 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 18, 2024, 18:27

marked the checklist item **결제 관련 모달창 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 18, 2024, 19:21

mentioned in commit b586b34db3781d6bb859ea255ffa35bd2d167747
