### ISSUE TITLE
✨[feature] 그룹 초대, 수락, 거절 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#83]
In GitLab by @jerry5230 on Sep 27, 2024, 11:06

## ✨[feature] 그룹 초대, 수락, 거절 기능 개발

그룹 가입 관련 기능 개발

### ✔️TODO
- [x] 알림 엔티티 생성
- [x] 그룹 초대 알림 엔티티 생성
- [x] 그룹 초대 수락 기능 개발
- [x] 그룹 초대 거절 기능 개발
- [ ] 그룹 초대 기능 개발

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 27, 2024, 11:07

created branch [`feature/back/teamInvite-suhwan`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2FteamInvite-suhwan) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 27, 2024, 16:23

mentioned in commit 2795bc1455c084048449968056a81776e06c88ab

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 27, 2024, 17:47

mentioned in commit aab8f71945d4d8e46ffac19ba957c8452d6e7dbb

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 01:19

mentioned in commit 587aecfc80360b165d058b8c51b45e9cd3751ecf

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 02:25

marked the checklist item **알림 엔티티 생성** as completed

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 02:25

marked the checklist item **그룹 초대 알림 엔티티 생성** as completed

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 02:25

marked the checklist item **그룹 초대 수락 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 02:25

marked the checklist item **그룹 초대 거절 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 02:25

mentioned in commit d8332f9ba8807f38de831de9605f369294323bc4

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 02:49

mentioned in commit b559fc6374d4657d2e669d2e5977481212563056

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 04:28

mentioned in commit 4e3dca87b9af2a002753120c786118b19f264f33

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 04:30

mentioned in commit 11f727a9f935fd89420f90451d74add22287c850

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 19:19

mentioned in commit 00fb9ee453e2b3d791abedd083d9cd9430752dbf

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 19:19

mentioned in commit dff303686fafd5b81cb97d951d011b8df907b220

**Comment by hyeon8571** [comment]
In GitLab by @jerry5230 on Sep 29, 2024, 19:24

mentioned in commit 863ac9ff97af6daa12439e81a27656e0fe076262
