### ISSUE TITLE
🐛[hotfix] 서비스 연동 정보 저장소 전환

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#84]
In GitLab by @w01085914442 on Sep 27, 2024, 12:13

### ✔️TODO
- [x] 서비스 연동 정보 저장소 전환(redis -> MySQL)
- [x] 그룹 연동 기능 개발
- [x] 예약 로직 변경

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 27, 2024, 12:14

created branch [`feature/back/connectInfo-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2FconnectInfo-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 28, 2024, 20:57

marked the checklist item **예약 로직 변경** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 28, 2024, 21:25

mentioned in commit 4cca75958c9d5f24fc15cfaafed020bb7e382fbc

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 29, 2024, 24:11

mentioned in commit 7af39429bf14d069bb5d5b3a082822768fa42694
