### ISSUE TITLE
✨[feature] 그룹 목록 페이지 구현

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#87]
In GitLab by @pjy7244 on Sep 27, 2024, 12:52

### ✔️TODO
- [x] 그룹 페이지 컴포넌트 분리
- [x] 그룹 목록 페이지 구현
- [x] 그룹 목록 관련 api연결

### 📌ETC
- 초기곡 선택 API 무한 호출 수정
- 엑세스토큰 갱신 수정
- 마이프로필에 임시 로그아웃 버튼 생성

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 28, 2024, 11:35

marked the checklist item **그룹 목록 페이지 구현** as completed

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 28, 2024, 11:36

mentioned in commit dfcdcb9c44d4af4f8cb4d522094e86471498c0c2

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 28, 2024, 11:40

mentioned in commit 233cfbccbbfc8547d4925afde955f8c49f9a6252

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 28, 2024, 12:05

mentioned in commit 130eba3e47cde660d429d536c6865d1db254a9ab

**Comment by hyeon8571** [comment]
In GitLab by @pjy7244 on Sep 30, 2024, 12:11

mentioned in commit 769c5108c2aa428eb0af844f6836f00de5d186fc

**Comment by hyeon8571** [comment]
In GitLab by @kminjin99 on Sep 30, 2024, 13:51

mentioned in commit 6b9e4e3900f805d300f1b611524773d1e7673046
