### ISSUE TITLE
✨[feature] 기록 조회 기능 개발 (가장 많이 부른)

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#9]
In GitLab by @eunjee0404 on Sep 16, 2024, 14:59

### ✔️TODO
- [x] 가장 많이 부른 곡 조회 (top3) 기능 개발
- [x] 가장 많이 부른 아티스트 조회 (전체) 기능 개발
- [x] 가장 많이 부른 장르 조회 (top3) 기능 개발

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 16, 2024, 15:01

created branch [`feature/back/historyMost-eunji`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2FhistoryMost-eunji) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 23, 2024, 24:31

marked the checklist item **가장 많이 부른 곡 조회 (top3) 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 23, 2024, 10:08

marked the checklist item **가장 많이 부른 아티스트 조회 (전체) 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 23, 2024, 10:08

marked the checklist item **가장 많이 부른 장르 조회 (top3) 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @eunjee0404 on Sep 23, 2024, 10:11

mentioned in commit 8993fbbede8fbc73ceedc02222740db82fc8cdc7

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 25, 2024, 09:32

mentioned in commit 0552a941be901e92c9c4fc066126434e562dc027
