### ISSUE TITLE
✨[feature] 사용자 부가 기능 개발

### ISSUE THREAD

**Issue by hyeon8571** [SongPicker/SongPicker#98]
In GitLab by @w01085914442 on Sep 30, 2024, 05:09

### ✔️TODO
- [x] 닉네임 조회 기능 개발
- [x] 아이디 찾기 기능 개발
- [x] 비밀번호 수정 기능 개발
- [x] 닉네임 수정 기능 개발
- [x] 전화번호 수정 기능 개발
- [x] 프로필 사진 수정 기능 개발
- [x] 비밀번호 인증 기능 개발

### 📌ETC
-

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 09:14

created branch [`feature/back/memerSub-seunghyeon`](/s11-bigdata-recom-sub1/S11P21D208/-/compare/develop...feature%2Fback%2FmemerSub-seunghyeon) to address this issue

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 17:53

marked the checklist item **닉네임 조회 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 17:53

marked the checklist item **아이디 찾기 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 17:53

marked the checklist item **비밀번호 수정 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 17:53

marked the checklist item **닉네임 수정 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 17:53

marked the checklist item **비밀번호 인증 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Sep 30, 2024, 17:53

mentioned in commit 600adafd0e987d9223425d9184db48202dc52a83

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 1, 2024, 16:35

marked the checklist item **프로필 사진 수정 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 1, 2024, 16:35

marked the checklist item **전화번호 수정 기능 개발** as completed

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 1, 2024, 16:37

mentioned in commit b5cee65915d21adfcc1a894fa1910fa07425dd68

**Comment by hyeon8571** [comment]
In GitLab by @w01085914442 on Oct 1, 2024, 16:39

mentioned in commit 2b5e450bf4b6450c099991b9f0705861de3a5ead
